#!/bin/sh

B='#18171cFF'  # blank
C='#18171cFF'  # clear ish
D='#17d495cc'  # default
T='#17d495FF'  # text
W='#f50d59bb'  # wrong
V='#bb00bbbb'  # verifying

i3lock                \
-c 18171c             \
--insidevercolor=$C   \
--ringvercolor=$V     \
\
--insidewrongcolor=$C \
--ringwrongcolor=$W   \
\
--insidecolor=$B      \
--ringcolor=$D        \
--linecolor=$B        \
--separatorcolor=$D   \
\
--textcolor=$T        \
--timecolor=$T        \
--datecolor=$T        \
--keyhlcolor=$W       \
--bshlcolor=$W        \
\
--screen 0            \
--clock               \
--indicator           \
--timestr="%H:%M:%S"  \
--timefont="Not Sans" \
--datestr="%A, %m %Y" \
--datefont="Noto Sans" \

# --veriftext="Drinking verification can..."
# --wrongtext="Nope!"
# --textsize=20
# --modsize=10
# --timefont=comic-sans
# --datefont=monofur
# etc
