vim.opt.cursorline = true
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.shiftwidth = 2
vim.opt.autoindent = true

--vim.opt.clipboard+=unnamedplus
vim.opt.tabstop = 2               -- number of visual spaces per TAB
vim.opt.softtabstop = 2           -- number of spaces in TAB when editing
vim.opt.shiftwidth = 2
vim.opt.expandtab = true               -- all tabs are spaces
vim.opt.splitright = true              -- open split buffers at right
vim.opt.autoindent = true
vim.opt.smartindent = true
vim.opt.smarttab = true
vim.opt.encoding = 'utf-8'
vim.opt.fileencoding = 'utf-8'
vim.opt.linespace = 0             -- don't insert extra pixels between rows
vim.opt.number = true                  -- show linenumbers
vim.opt.cursorline = true              -- highlight current line
vim.opt.wildmenu = true                -- visual autocomplete for command menu
vim.opt.wrap = false
vim.opt.lazyredraw = true             -- redraw only when necessary
vim.opt.showmatch = true              -- highlight match {[()]}
vim.opt.incsearch = true              -- Find the next match as we type the search
vim.opt.hlsearch = true               -- highlight matches search
vim.opt.history = 100
vim.opt.backspace = "indent,eol,start"
vim.opt.swapfile = false
vim.opt.hidden = true
