
(global-auto-revert-mode 1)
(global-hl-line-mode t)
(global-linum-mode t)
;;(global-whitespace-mode t)
(setq column-number-mode t)
(setq size-indication-mode t)
(setq-default indent-tabs-mode nil)
(setq-default tab-width 2)
(setq visible-bell t)
(setq ring-bell-function 'ignore)
(setq show-paren-mode t)
(set-default 'truncate-lines t)
(defalias 'yes-or-no-p 'y-or-n-p)
(savehist-mode)
