- name: Ubuntu setup
  hosts: all
    #  become: true
  tasks:
    #   - name: Add chrome repository into sources list
    #     ansible.builtin.apt_repository:
    #       repo: deb http://dl.google.com/linux/chrome/deb/ stable main
    #       state: present
    - name: Run the equivalent of "apt-get update"
      ansible.builtin.apt:
        update_cache: yes
    - name: install baseline
      ansible.builtin.apt:
        pkg:
        - software-properties-common
        - curl
        - tmux
        - tldr
        - fzf
        - awscli
        - ripgrep
        - zsh
        - ubuntu-desktop
          #- chrome
    - name: install i3
      ansible.builtin.apt:
        pkg:
        - i3
        - xinit
        - polybar
        - feh
    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: yes
