- name: Ubuntu setup
  hosts: localhost
    #  become: true
  tasks:
    - name: Run the equivalent of "apt-get update"
      ansible.builtin.apt:
        update_cache: yes
    - name: install baseline
      ansible.builtin.apt:
        pkg:
        - software-properties-common
        - curl
        - xclip
        - tmux
        - tldr
        - fzf
        - awscli
        - ripgrep
        - zsh

    - name: Add nvim ppa:repo
      become: true
      ansible.builtin.apt_repository:
        repo: ppa:neovim-ppa/unstable
    - name: Run the equivalent of "apt-get update"
      become: true
      ansible.builtin.apt:
        update_cache: yes
    - name: install neovim 
      become: true
      ansible.builtin.apt:
        pkg:
          - neovim

    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: yes
